//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stat.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int id_com { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public int User_id { get; set; }
        public int State_id { get; set; }
    
        public virtual States States { get; set; }
        public virtual Users Users { get; set; }
    }
}
